FONT_FAMILY = 'Segoe UI'
FONT_SIZE_TITLE = 40
FONT_SIZE_SUBTITLE = 18
FONT_SIZE_NORMAL = 12

PAD_X_TITLE = 20
PAD_Y_TITLE = 30
PAD_X_SUBTITLE = 10
PAD_Y_SUBTITLE = 10
PAD_X_NORMAL = 5
PAD_Y_NORMAL = 5
